name: $hyoo_crus_app

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
  - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hyoo-ru/mam_build@master2
      with:
        package: 'hyoo/crus'
        modules: 'app/run'
    - uses: hyoo-ru/gh-deploy@v4.4.1
      if: github.ref == 'refs/heads/master'
      with:
        folder: 'hyoo/crus/app/run/-'

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image and Push to GHCR
      uses: GlueOps/github-actions-build-push-containers@v0.4.5
      with:
        dockerfile: 'docker/Dockerfile'
